name: test_retrieval
on: [push]
jobs:
  run_retrieval_gmi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install -e .
      - run: cd test; ./test_retrieval_gmi.sh
      - run: cd test; ./test_retrieval_gmi_hr.sh
      - run: cd test; ./test_retrieval_tmi.sh
      - run: cd test; ./test_retrieval_f15.sh
      - run: cd test; ./test_retrieval_f17.sh
